wmixvideo/nfe

src/main/java/com/fincatto/nfe310/NFeConfig.java, src/main/java/com/fincatto/nfe310/webservices/SocketFactoryDinamico.java, src/main/java/com/fincatto/nfe310/webservices/WSFacade.java, src/test/java/com/fincatto/nfe310/FabricaDeObjetosFake.java
Alterado para receber o certificado em bytearray, pois o usuário pode guardá-lo em um banco de dados e não somente em arquivos;
Inserido o SocketFactoryDinamico para quando utilizar a classe WSFacade não setar mais o certificado no System, mas criar um Protocol para fazer a comunicação com o Sefaz;
Alterado para recuperar o certificado em bytearray, porém se o mesmo não existir recupera o caminho do certificado
=> Alterado para receber o certificado em bytearray

src/main/java/com/fincatto/nfe310/assinatura/AssinaturaDigital.java
Remoção do inputStream para não dar mais o erro: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Byte inválido 2 da sequência UTF-8 do byte 3.
Esse problema normalmente está relacionado a caracteres especiais ou acentuados dentro do XML. @see http://goo.gl/42aPOh
=> Correção ao assinar xml quando há caracteres especiais ou acentuados

src/main/java/com/fincatto/nfe310/utils/NFGeraChave.java
Segundo o manual de orientação do contribuinte (v6.00): "O código numérico que compõe a Chave de Acesso é um número aleatório gerado pelo emitente para cada NF-e para evitar acessos indevidos da NF-e. (v2.0)"
A sugestão de alteração é para que nos casos em que o código não tenha sido informado, o sistema gere um código automaticamente.
=> Código aleatório automaticamente

src/main/java/com/fincatto/nfe310/webservices/WSCancelamento.java, src/main/java/com/fincatto/nfe310/webservices/WSCartaCorrecao.java
Ao analisar o emissor gratuito verifiquei que o valor atribuído ao idLote para eventos de carta correção e cancelamento é o milissegundos (ex: 1467724330155) da data atual.
Documentação da NF-e para o idLote:
Identificador de controle do Lote de envio do Evento. Número sequencial autoincremental único para identificação do Lote. A responsabilidade de gerar e controlar é exclusiva do autor do evento. O Web Service não faz qualquer uso deste identificador.
=> Alteração idLote para eventos de carta correção e cancelamento

src/main/java/com/fincatto/nfe310/classes/evento/NFEnviaEventoRetorno.java, src/test/java/com/fincatto/nfe310/classes/evento/cancelamento/NFEnviaEventoRetornoCancelamentoTest.java
Seguindo a sugestão do Diego foi adicionada uma anotação @Convert(StringNullConverter.class) ao atributo idLote da classe com.fincatto.nfe310.classes.evento.NFEnviaEventoRetorno para resolver o problema na SVAN que está enviando o atributo (idLote) vazio.
Criei um teste para o converter.
=> Correção de problema para cancelar NFe na SVAN

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java, src/main/java/com/fincatto/nfe310/parsers/NotaFiscalChaveParser.java, src/main/java/com/fincatto/nfe310/webservices/WSLoteEnvio.java, src/test/java/com/fincatto/nfe310/classes/NFAutorizador31Test.java
Para o envio em contingência SVC-RS ou SVC-AN:
- Definir no NfeConfig o tipo de emissão:
```
@Override
public NFTipoEmissao getTipoEmissao() {
return NFTipoEmissao.CONTINGENCIA_SVCRS;
}
```
- Setar tipo de emissão da nota de acordo com o ambiente
- Setar a Justificativa de entrada em contingência .
Consulta e cancelamento de notas enviadas em contingência tem seu ambiente identificado automaticamente através da chave, não havendo qualquer diferença de uso em relação ao ambiente normal.
=> Alteração para envio nos ambientes SVC RS e AN

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java, src/test/java/com/fincatto/nfe310/classes/NFAutorizador31Test.java
Foi criado um item no enum chamado PI mesclando as URLs do SVAN para NF-e com SVRS para NFC-e.
=> Mesclar SVAN com SVRS no Piauí

src/main/java/com/fincatto/nfe310/classes/NFNotaInfoImpostoTributacaoICMS.java, src/main/java/com/fincatto/nfe310/classes/nota/NFIndicadorPresencaComprador.java
adicionado método getDescricao em NFNotaInfoImpostoTributacaoICMS e NFIndicadorPresencaComprador, para ficar de acordo com algumas outras classes ENUM que continham este método e me parece que deveria ser adotado como um padrão
=> adicionado método getDescricao em NFNotaInfoImpostoTributacaoICMS e NFIndicadorPresencaComprador

src/main/java/com/fincatto/nfe310/webservices/WSLoteConsulta.java
Observei que a consulta por chave não retornava a rejeição quando a nota não era autorizada em contingencia. Retornava "Rejeição 217: NF-e não consta na base de dados da SEFAZ". Ao consultar por lote é possível obter o estado da nota nas situações onde não é autorizada.
(PR com correção da tabulação que estava sendo entendida como espaço)
=> Alteração para permitir a consulta de lotes em ambiente de contingencia

src/main/java/com/fincatto/nfe310/webservices/WSLoteEnvio.java
Eu acabei verificando um erro para envio de lote onde era retirado o campo CDATA da tag qrCode, o problema é na hora de construir o OMElement, na linha: final OMElement ome = AXIOMUtil.stringToOM(documento);
Eu fiz uma solução mudando a forma de construir o OMElement para manter o campo CDATA.
final XMLInputFactory factory = XMLInputFactory.newInstance();
factory.setProperty(XMLInputFactory.IS_COALESCING, false);
XMLStreamReader reader = factory.createXMLStreamReader(new StringReader(documento));
StAXOMBuilder builder = new StAXOMBuilder(reader);
final OMElement ome = builder.getDocumentElement();
A propriedade IS_COALESCING como false que mantém o CDATA.
Segue o pull request.
=> Correção na forma de construir o OMElement a partir do XML de envio de Lote para manter os campos CDATA.

README.md
Tentamos durante 3 dias executar o método que faz a consulta do status do webService para retornar a mensagem:
"107 serviço em operação"
Não obtivemos êxito sempre recebiamos este erro na execução:
`
16:45:27,882 INFO [org.apache.axis2.transport.http.HTTPSender] (http--0.0.0.0-8080-4) Unable to sendViaPost to url[https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx]: org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) [axis2-kernel-1.6.4.jar:1.6.4]
at …
=> Sugestão para gerar a cadeia de certificados da unidade certificadora

src/main/java/com/fincatto/nfe310/classes/NFAmbiente.java, src/main/java/com/fincatto/nfe310/converters/NFAmbienteConverter.java
Criada a classe NFAmbienteConverter para permitir a correta conversão do enum NFAmbiente a fim de serializar o objeto NFProtocolo para utiliza-lo na geração da danfe.
@lucas85cunha 
@ambroiler
=> Inclusão de converter para Serializar objeto NFAmbiente

src/main/java/com/fincatto/nfe310/webservices/NFSocketFactory.java
Usando a mesma lógica da assinatura, quando especificado usar o alias caso contrário pegar a
primeira entrada da KeyStore conforme discussão #267
=> Removendo busca do alias dentro da KeyStore

src/main/java/com/fincatto/nfe310/classes/evento/cartacorrecao/NFProtocoloEventoCartaCorrecao.java, src/test/java/com/fincatto/nfe310/classes/cartacorrecao/NFProtocoloEventoCartaCorrecaoTest.java
Criado estrutura do Protocolo do Evento da CC-e. É praticamente a mesma estrutura do protocolo do evento de cancelamento, entretanto, devido as tipagens da NF-e, foi necessário criar um específico.
=> Criado estrutura do Protocolo do Evento da CC-e.

src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java
As URL's para a geração de QRCode do cupom para a PB foram alteradas. O http/https é obrigatório.
Homologação: https://www.receita.pb.gov.br/nfcehom
Produção: https://www.receita.pb.gov.br/nfce
Fonte: http://nfce.encat.org/desenvolvedor/qrcode/
=> Modificando as URL's de envio de Cupom do estado da PB

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java, src/test/java/com/fincatto/nfe310/classes/NFAutorizador31Test.java
1) Adicionando autorizador para envio de notas nas contingências fsda e offline; 
2) Adicionando testes
=> Adicionando autorizador para envio de notas nas contingências FSDA e offline

src/main/java/com/fincatto/documentofiscal/nfe/NFeConfig.java, src/main/java/com/fincatto/documentofiscal/nfe310/webservices/WSLoteConsulta.java, src/main/java/com/fincatto/documentofiscal/nfe310/webservices/WSLoteEnvio.java, src/main/java/com/fincatto/documentofiscal/nfe310/webservices/WSStatusConsulta.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSLoteConsulta.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSStatusConsulta.java
Retira static do método getVersao em configurações da Nota, para poder configurar com a nota 4.00 e evitar o erro:
<cStat>215</cStat><xMotivo>Falha no schema XML</xMotivo><cUF>41</cUF><dhRecbto>2018-03-02T08:32:21-03:00</dhRecbto><xObs>org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 72; cvc-pattern-valid: Value &apos;3.10&apos; is not facet-valid with respect to pattern &apos;4\.00&apos; for type &apos;TVerConsStatServ&apos;.</xObs>
=>  Retira static do método getVersao em configurações da Nota, para poder configurar com a nota 4.00

pom.xml
Alterado a versão da biblioteca slf4j para 1.7.25 por incompatibilidade com Jetty 9.3 que é utilizado pelo app engine do Google.
=> Alterado a versão da biblioteca slf4j para 1.7.25

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java
Correção das URLs dos autorizadores de MS e SVRS da NFC-e. Estavam com o endereço da versão 3.10.
Resolução do problema relatado nesta questão: https://github.com/wmixvideo/nfe/issues/428
=> Correção de URLs

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProdutoCombustivel.java, src/main/java/com/fincatto/documentofiscal/validadores/BigDecimalParser.java, src/test/java/com/fincatto/documentofiscal/validadores/BigDecimalParserTest.java
Alterado tamanho dos campos "percentualGLPDerivadoPetroleo", "percentualGasNaturalImportado" e "percentualGasNaturalNacional", da classe "NFNotaInfoItemProdutoCombustivel", de acordo com a Nota Técnica 2016.002 - v 1.50.
=> Tamanho campos pGLP, pGNn e pGNi - Nota Técnica 2016.002 - v 1.50.

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFProtocoloInfo.java
Classe: src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFProtocoloInfo.java
Como o código já está mapeado no enum NFRetornoStatus e neste enum já tem a descrição, foi retirado a obrigatoriedade de xMotivo estar preenchido no retorno do WS da SEFAZ.
=> Retirado a obrigatoriedade do retorno de xMotivo.

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java
Alteração na URL de consulta da NFC-e no ambiente de homologação para o estado do Pará. A URL continha 86 caracteres, o que feria a regra de validação que aceita de 25 a 85 caracteres.
=> NFC-e Homologação Pará - Validação URL de consulta da chave

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
Com o ajuste para emissão com o `NFGeraQRCode20`, acabou não levando um Workarround que existia no `NFGeraQRCode`  para a URL do Paraná, o que está certo pois era um Workarround. Mudei então as Url's do QRCode para o Paraná na classe `DFUnidadeFederativa`. Testado emissão de nota com o QRCode 2 para o Paraná Offline e Online, com essa nova URL montou certo e o link abriu a nota corretamente.
Para conhecimento, o Workarround que existia era esse:
```
/* FIXME TODO Workaround para corrigir erro :
*<cStat>395</cStat><xMotivo>Endereco do site da UF da Consulta via QR-Code diverge do previsto. Novo endereco:http://www.fazenda.pr.gov.br/nfce/qrcode</xMotivo>
* corrigir em DFUnidadeFederativa quando a URL da versao 3.10 do PR for desabilitada.
*/ …
```
=> Alteração Url QrCode Paraná

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/consulta/NFNotaConsultaRetorno.java
Em algumas rejeições a sefaz do Paraná, não retorno os atributos versao e chNFe, sendo assim ocorre erro ao fazer o parce do XML, e consequentemente não sendo possível identificar o código de retorno.
=> Obrigatoriedade atributos NotaConsultaRetorno

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java
Testes de envio de notas à SEFAZ/AM funcionam com estas modificações. Sem elas ocorre um erro semelhante a este: The endpoint reference (EPR) for the Operation not found is https://nfce.sefaz.am.gov.br:443/nfce-services/services/NfeAutorizacao and the WSA Action = http://www.portalfiscal.inf.br/nfe/wsdl/.
Suspeito que isto ocorra porque o endpoint da versão 3.10 ainda está no ar e esteja sendo usado para tratar as requisições para a URL https://nfce.sefaz.am.gov.br:443/nfce-services/services/NfeAutorizacao.
=> Ajuste nas URLs relacionadas a autorização de NFC-e no Amazonas

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
Estava dando erro na versão do QRCode devido a URL está desatualizada.
=> Alteradas as URLs do QRCode para o Maranhão

src/main/java/com/fincatto/documentofiscal/nfe310/classes/nota/NFNotaInfoItemProduto.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProduto.java, src/test/java/com/fincatto/documentofiscal/nfe310/FabricaDeObjetosFake.java, src/test/java/com/fincatto/documentofiscal/nfe310/classes/nota/NFNotaInfoItemProdutoTest.java, src/test/java/com/fincatto/documentofiscal/nfe400/FabricaDeObjetosFake.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProdutoTest.java
O atributo da classe NFNotaInfoItemProduto é compoe e o método set estava com typo, Campoe. Foi corrigido este typo nos dois métodos das duas classes e corrigido também o uso do método nos testes.
=> Corrige typo 'Campoe' para 'Compoe' em métodos Set e de teste unitário

src/main/java/com/fincatto/documentofiscal/nfe400/classes/evento/cancelamento/NFRetornoInfoCancelamento.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/consulta/NFProtocoloEvento.java, src/main/java/com/fincatto/documentofiscal/transformers/DFLocalDateTimeTransformer.java
Alteração do nome do atributo ID para Id conforme especificação em manual. Já a alteração na classe DateTimeFormatter e devido a SEFAZ estar retornando os milissegundos e quando se fazia o parser era ocasionado erro.
=> Ajustes para funcionamento correto em MG

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
Inclusão da URL para gerar nota para o Estado de Alagoas.
Alteração na URL QRCODE para o Estado do Rio de Janeiro, estava retornando "Rejeição 395: Endereço do site da UF da Consulta via QR-Code diverge do previsto"
=> Inclusão URL QRCODE para Alagoas e alteração URL QRCODE Rio de Janeiro

src/main/java/com/fincatto/documentofiscal/nfe400/classes/lote/envio/NFLoteEnvioRetorno.java
Quando a nota é emitida para SVRS e o retorno é uma rejeição de consumo indevido, no XML o nó cUF vem vazio e por esse motivo ocorre uma falha ao tentar fazer o parse para o objeto. Exemplo do retorno de rejeição que causou o erro:
`<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SVRSnfce201908091113</verAplic><cStat>656</cStat><xMotivo>Rejeicao: Consumo indevido pelo aplicativo da empresa [Quantidade rejeicoes: 973, NF-e: 22191007272825001690651050000032289661613580]</xMotivo><cUF /><dhRecbto>2019-11-20T19:49:57-03:00</dhRecbto></retEnviNFe>`
=> Remove obrigatoriedade da UF

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java
Bom dia,
Conforme o título a alteração realizada apenas adiciona os estados do Pará e Piaui ao SVRS (Pará já estava, mas como necessitava adicionar o estado do Piaui ao SVRS, vi que o estado do Pará estava fora do padrão adotado e já tentei normalizar isso).
Pelo que pesquisei o estado do Piauí já emite há algum tempo via SVRS... (Tive problemas ao emitir uma nota em ambiente de produção utilizando o SVAN e por isso notei esse problema)
http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=
=> Adiciona Pará e Piaui ao SVRS

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFMeioPagamento.java
Pessoal, o valor de duplicata mercantil foi removido do enum NFMeioPagamento impossibilitando o carregamento de XML's que possuem esse valor. Estou adicionando novamente tal valor no enum.
=> Adicionando valor de DUPLICATA MERCANTIL ao enum NFMeioPagamento

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
- Inclusão das Urls.
- Alteração dos Testes unitários.
Realizado Teste de emissão de NFCe em ambiente de Produção com configuração de SC e a nota foi emitida / cancelada com sucesso.
Acredito que resolve a Issue #706
=> Inclusão da URL correta para emissão de NFCe em SC

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoFormaPagamento.java
Corrige a ordem do xPag que afeta a issue #750 
O xPag deve ter precedência sobre a tag vPag, com isso é possível emitir Notas com o tPag 99 (Outros).
E apenas relembrando que a data prazo para essa modificação estar vigente em Produção é dia 01/09. Caso contrário não será possível emitir notas com o meio de pagamento "Outros".
=> Corrige ordem da tag xPag (deve ter precedência sobre a tag vPag)

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFNotaInfoCombustivelTipo.java
Não consegui realizar a leitura de algumas notas, pois recebi os tipos de combustíveis "0" e "19". Como não encontrei a tabela online, realizamos o contato com a Sefaz e conseguimos a seguinte resposta:
[SEI_MINFRA - 4515457 - Nota Informativa.pdf](https://github.com/wmixvideo/nfe/files/7143750/SEI_MINFRA.-.4515457.-.Nota.Informativa.pdf)
Como não consta o "0", tentei seguir o padrão da lib e adicionei como "Outros". De resto, apenas atualizei com a tabela recebida.
=> Atualizando tipos de combustíveis.

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
Olá pessoal,
Fiz a alteração da URL para geração do QRCode para o Estado do Acre, Ambiente de produção.
Fizemos vários testes emitindo NFCE em ambiente de produção para clientes neste estado, todos com sucesso.
=> Mudança da URL do Qrcode para o estado ACRE, ambiente produção

src/test/java/com/fincatto/documentofiscal/mdfe3/FabricaDeObjetosFakeMDFe.java
Hi,
This PR fixes 1 violations of [Sonar Rule 2111: '"BigDecimal(double)" should not be used'](https://rules.sonarsource.com/java/RSPEC-2111). This is done without introducing any new violations of Sonar rules.
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2111](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#bigdecimaldouble-should-not-be-used-sonar-rule-2111).
P.S.: Note that this PR is not created/submitted by a bot. If you have any feedback, please leave them as comments.
=> Fix violations of Sonar rule 2111

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProdutoMedicamento.java
A tag xMotivoIsencao não é obrigatório, porém quando informada causava um erro de validação.
`org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1846; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'vPMC'. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":xMotivoIsencao}'.`
Esse PR altera a ordem do atributo, foi testado em ambiente de homologação e o problema foi resolvido.
=> Altera a ordem do atributo xMotivoIsencao

README.md
Atualização no exemplo, pois houve mudança nas classes UF que foi de "NFUnidadeFederativa" para "DFUnidadeFederativa"
=> Atualização no exemplo, pois houve mudança nas classes UF que foi de "NFUnidadeFederativa" para "DFUnidadeFederativa"

src/main/java/com/fincatto/documentofiscal/cte/webservices/distribuicao/WSDistribuicaoCTe.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSFacade.java
Olá,
Verifiquei que o método `consultar` do `WSDistribuicaoCTe` estava retornando um `NFDistribuicaoIntRetorno` em vez do `CTDistribuicaoIntRetorno`, que é o tipo correto e já existente no projeto. Isso fazia com que, ao pegarmos o objeto de retorno e convertê-lo para XML, o resultado ficava com o namespace errado (de nfe em vez de cte).
=> Corrigido tipo de retorno do método WSDistribuicaoCTe.consultar para CTDistribuicaoIntRetorno

src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSNotaConsulta.java
A consulta de situação do CT-e deve ser feita na UF em que ele foi emitido originalmente e não na UF/ambiente da configuração atual. Esse mesmo tratamento já é feito na classe equivalente da NF-e.
=> Corrigido para consultar o CT-e na UF em que ele foi emitido

src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/CTeDetalhamentoEvento.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/CTeEventoRetorno.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/CTeInfoEventoRetorno.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/cancelamento/CTeEnviaEventoCancelamento.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/cartacorrecao/CTeEnviaEventoCartaCorrecao.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/comprovanteentrega/CTeEnviaEventoCancelamentoComprovanteEntrega.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/comprovanteentrega/CTeEnviaEventoComprovanteEntrega.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/desacordo/CTeEnviaEventoPrestacaoEmDesacordo.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/epec/CTeEnviaEventoEpec.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/gtv/CTeEnviaEventoGtv.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/multimodal/CTeEnviaEventoRegistroMultimodal.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSCancelamento.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSCancelamentoComprovanteEntrega.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSCartaCorrecao.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSComprovanteEntrega.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSEpec.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSGtv.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSPrestacaoEmDesacordo.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSRecepcaoEvento.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSRecepcaoLote.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSRegistroMultimodal.java, src/main/java/com/fincatto/documentofiscal/validadores/DFXMLValidador.java
No meu PR anterior (#902) esqueci de corrigir um erro na geração do atributo "Id" dos eventos e o tratamento pra geração do EPEC também não estava 100%. Fiz essas correções aqui e também tratei para validar o XML gerado pelos eventos contra os schemas do CT-e 3.00 antes do envio.
=> CT-e: Corrige id dos eventos, geração do EPEC e incluída validação de schema nos eventos

src/main/java/com/fincatto/documentofiscal/nfe/classes/distribuicao/NFDistribuicaoDocumentoZip.java
corrigido para nao obrigar nsu no retorno do consulta distruicao, pois em alguns casos este campo vem null
=> ajuste consulta distruicao

src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/CTeNotaInfoCTeNormalInfoCTeSubstituicao.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/consulta/CTeNotaConsultaRetorno.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSPrestacaoEmDesacordo.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSRecepcaoEvento.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/nota/consulta/CTeNotaConsultaRetorno.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSCancelamentoPrestacaoEmDesacordo.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSPrestacaoEmDesacordo.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSRecepcaoEvento.java
- Ajustado evento de prestação em desacordo para receber o sequencial do evento porque é permitida a geração de até 20 eventos
- Ajustado cancelamento do evento de prestação em desacordo (existe apenas no 4.00) para receber o CPF/CNPJ do autor do evento pois assim como o evento de desacordo ele é gerado pelo tomador do serviço, então não dá pra extrair essa informação da chave de acesso do CT-e
- Corrigidos atributos opcionais na parte de CT-e de substituição no CT-e 3.00
- Incluído getter/setter que faltava na CTeNotaConsultaRetorno
- Melhorada mensagem de erro gerada quando é informado um sequencial de evento maior que o permitido
=> Correções diversas nas classes do CT-e

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS53.java
Pequeno erro de digitação, estava como "v**Icms**MonoOp" em vez de "v**ICMS**MonoOp" e não era possível ler XMLs com essa tag.
=> Corrigido mapeamento da tag vICMSMonoOp na NF-e

src/main/java/com/fincatto/documentofiscal/cte300/classes/evento/CTeDetalhamentoEvento.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/CTeNotaInfoCTeNormalDocumentosAnterioresEmissorDocumentosAnteriores.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/CTeProcessado.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/consulta/CTeNotaConsultaRetorno.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/nota/consulta/CTeProtocoloEvento.java, src/main/java/com/fincatto/documentofiscal/cte300/classes/os/CTeOSProcessado.java, src/main/java/com/fincatto/documentofiscal/cte300/utils/CTeGeraChave.java, src/main/java/com/fincatto/documentofiscal/cte300/utils/CTeGeraQRCode.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/evento/CTeDetalhamentoEvento.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/nota/CTeNotaInfoCTeNormalDocumentosAnterioresEmissorDocumentosAnteriores.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/nota/CTeProcessado.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/nota/consulta/CTeNotaConsultaRetorno.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/nota/consulta/CTeProtocoloEvento.java, src/main/java/com/fincatto/documentofiscal/cte400/classes/os/CTeOSProcessado.java, src/main/java/com/fincatto/documentofiscal/cte400/utils/CTeGeraChave.java, src/main/java/com/fincatto/documentofiscal/cte400/utils/CTeGeraQRCode.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/WSRecepcaoCTeOS.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/gerado/CTeConsultaV4Stub.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/gerado/CTeRecepcaoEventoV4Stub.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/gerado/CTeRecepcaoOSV4Stub.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/gerado/CTeRecepcaoSincV4Stub.java, src/main/java/com/fincatto/documentofiscal/cte400/webservices/gerado/CTeStatusServicoV4Stub.java, src/main/resources/schemas/PL_CTe_400/cteTiposBasico_v4.00.xsd
Identifiquei mais algumas correções necessárias enquanto testava a biblioteca com uma série de situações diferentes relacionadas ao CT-e, separei cada correção/melhoria em seu commit com mais detalhes.
=> Correções diversas no CT-e

src/main/java/com/fincatto/documentofiscal/cte300/classes/CTAutorizador31.java
Ajustando link do QRCode conforme documentação da SEFAZ de MG para ambiente de homologação e documento fiscal CTe.
#927
=> ajuste link qrcode sefaz mg para ambiente de homologacao

src/main/java/com/fincatto/documentofiscal/mdfe3/webservices/WSIncluirDFe.java
Com a descricao 'Inclusao de DF-e' estava dando erro de validação, informando o  valor esperado como 'Inclusao DF-e'. Foi apenas removido a o 'de'.
=> Alterado descricao do evento de inclusao de DFe.

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS51.java
Adicionado o campo cBenefRBC na classe do NFNotaInfoItemImpostoICMS51 conforme NT2019_001_v1_64 
Adicionado logo abaixo do pRedBC para validar corretamente na SEFAZ se colocar fora da ordem não passa na validação do schema
=> Adicionado o campo cBenefRBC no NFNotaInfoItemImpostoICMS51

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFNotaInfoTipoVeiculo.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFNotaInfoTipoVeiculoTest.java
o campo no XML aceita por exemplo "01" e "1" para o mesmo caso, por isso é feito as conversões para int para comparar o numero
=> ajustado conversao de codigo para tipo veiculo

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoSuplementar.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qrcode30/NFGeraQRCode30.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qrcode30/NFGeraQRCodeContingenciaOffline30.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qrcode30/NFGeraQRCodeEmissaoNormal30.java, src/main/java/com/fincatto/documentofiscal/validadores/DFStringValidador.java
Implementamos as Classe para o Qr-Code 3.0 conforme a nova nota técnica referida.
Atualizamos a validação do tamanho do Qr-Code conforme a nova regra da NT.
Não atualizamos a chamada do Qr-Code no método getLoteAssinado da classe WSLoteEnvio no pacote com.fincatto.documentofiscal.nfe400.webservices. Mantivemos o uso do Qr-Code 2.0 porque não sabemos como deveria ser feita a parametrização conforme os padrões do projeto.
=> Classes referente ao Qr-Code 3.0 conforme Nota Técnica 2025.001 v.1.01
