wmixvideo/nfe

src/main/java/com/fincatto/nfe310/webservices/WSStatusConsulta.java, src/main/java/com/fincatto/nfe310/webservices/statusservico/consulta/NfeStatusServico2Stub.java
Namespace é validado no sefaz do PR e PE, removido para evitar problemas
=> Removido namespace

src/main/java/com/fincatto/nfe310/webservices/gerado/NfeAutorizacaoStub.java, src/main/java/com/fincatto/nfe310/webservices/gerado/NfeInutilizacao2Stub.java, src/main/java/com/fincatto/nfe310/webservices/gerado/NfeRetAutorizacaoStub.java, src/main/java/com/fincatto/nfe310/webservices/gerado/RecepcaoEventoStub.java
Removido namespaces por causa ocasionava problemas de comunicação com
as SEFAZ do PR e PE
=> Removido namespaces

src/main/java/com/fincatto/nfe310/webservices/WSFacade.java
Nao existe a funcionalidade de processamento sincrono, para evitar
problemas com desavisados, foi adicionado uma excecao.
=> Adicionado lancamento de excecao para processamento sincrono

src/main/java/com/fincatto/nfe310/webservices/WSCartaCorrecao.java, src/main/java/com/fincatto/nfe310/webservices/WSFacade.java
=> Adicionado numero sequencial de evento na carta de correcao

src/main/java/com/fincatto/nfe310/parsers/NotaParser.java, src/test/java/com/fincatto/nfe310/FabricaDeObjetosFake.java, src/test/java/com/fincatto/nfe310/integracao/ValidacaoXML.java, src/test/java/com/fincatto/nfe310/parsers/NotaParserTest.java
Adicionado parser para nota processada
Criado teste de unidade para Parser de nota
=> Adicionado parser para nota processada

src/main/java/com/fincatto/nfe310/transformers/NFLocalDateTransformer.java, src/test/java/com/fincatto/nfe310/transformers/NFLocalDateTransformerTest.java
=> Adicionado novo formato no parse de LocalDate

src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java, src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoDestinatario.java, src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoExportacao.java, src/test/java/com/fincatto/nfe310/classes/NFUnidadeFederativaTest.java, src/test/java/com/fincatto/nfe310/classes/nota/NFNotaInfoDestinatarioTest.java, src/test/java/com/fincatto/nfe310/classes/nota/NFNotaInfoExportacaoTest.java
Olá!
Estou implementando a APi de vocês no meu projeto de NFe. Muito bacana! Vcs estão de parabéns! No entanto, encontrei alguns empecilhos na emissão de NFe para cliente no exterior e os corrigi de acordo com a nota técnica.
Até mais!!
=> Colaboração

README.md
Correções de algumas palavras no README.md.
=> Correções de algumas palavras no README.md

.travis.yml, src/main/java/com/fincatto/nfe310/classes/evento/cancelamento/NFInfoCancelamento.java, src/main/java/com/fincatto/nfe310/classes/evento/cancelamento/NFInfoEventoCancelamento.java, src/main/java/com/fincatto/nfe310/validadores/xsd/XMLValidador.java, src/main/java/com/fincatto/nfe310/webservices/WSCancelamento.java, src/test/java/com/fincatto/nfe310/FabricaDeObjetosFake.java, src/test/java/com/fincatto/nfe310/classes/evento/cancelamento/NFEnviaEventoCancelamentoTest.java, src/test/java/com/fincatto/nfe310/classes/evento/cancelamento/NFEventoCancelamentoTest.java, src/test/java/com/fincatto/nfe310/classes/evento/cancelamento/NFInfoEventoCancelamentoTest.java, src/test/java/com/fincatto/nfe310/validadores/xsd/XMLValidadorTest.java
Melhorado cobertura de codigo.
Removido instrução desnecessária no .travis.yml
Corrigido nomeclatura do getter fora do padrao
=> Melhorado cobertura de testes

src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoICMSTotal.java, src/test/java/com/fincatto/nfe310/FabricaDeObjetosFake.java, src/test/java/com/fincatto/nfe310/classes/nota/NFNotaInfoICMSTotalTest.java
Adicionada propriedade "baseCalculoICMSST" e depreciada propriedade "valor"
=> Alteração de nomenclatura "valor" para "baseCalculoICMSST" (NFNotaInfoICMSTotal)

src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoCartao.java
para deixar os atributos do cartão cnpj, o tBand  o cAut como require = false
=> Alteração na forma de pagamento

pom.xml, src/main/resources/danfe/danfeR3.jrxml
1. Paliativo para problemas de compilação do jasperreports no Java 8.
2. Ajustes nas fontes utilizadas no PDF.
=> Ajustes compilação do relatorio

src/main/java/com/fincatto/nfe310/classes/danfe/NFDanfeReport.java, src/test/java/com/fincatto/nfe310/classes/danfe/NFGeraDanfeTest.java
Ajustando teste de existencia do arquivo e retorno do método de geração.
=> Alterando retorno do método de geração do danfe para byte[].

src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java
PR conforme solicitado no ticket https://github.com/wmixvideo/nfe/issues/202
=> Ajuste da URL do QR Code para o Amazonas

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java
Bem pessoal, estou iniciando no projeto, encontrei algumas dificuldades ao testar o envio de NFC-e para o estado do Amazonas, verifiquei que as URLs do WS no projeto não estavam atualizadas.
=> Alteração dos endereços do WebService de NFCe do Amazonas

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java, src/test/java/com/fincatto/nfe310/classes/NFAutorizador31Test.java
Adicionar a opção MA (Maranhão) a classe NFAutorizador31.
=> Mesclar SVAN com SVRS no Maranhão

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java
Alteração nas URLs para funcionamento da NFC-e no estado de SP
=> URL WEBSERVICES - AMBIENTE DE PRODUÇÃO PARA O ESTADO SP

src/main/java/com/fincatto/nfe310/classes/NFNotaSituacaoOperacionalSimplesNacional.java
Criado método getDescricao em NFNotaSituacaoOperacionalSimplesNacional
=> Adicionado método getDescricao em

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/Any.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/NFDownloadNFe.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/NFDownloadNFeRetorno.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/NFDownloadNFeRetornoInfo.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/NFDownloadNFeRetornoInfoProcNfe.java, src/main/java/com/fincatto/nfe310/classes/evento/downloadnf/NFDownloadNFeRetornoInfoProcNfeGrupoZip.java, src/main/java/com/fincatto/nfe310/webservices/WSDownladNF.java, src/main/java/com/fincatto/nfe310/webservices/WSFacade.java, src/main/java/com/fincatto/nfe310/webservices/downloadnf/NfeDownloadNFCallbackHandler.java, src/main/java/com/fincatto/nfe310/webservices/downloadnf/NfeDownloadNFStub.java
Ainda não foi possível gerar os testes, mas já estou utilizando na aplicação.
=> Implementação do serviço DownloadNF #107

src/main/java/com/fincatto/nfe310/classes/NFAutorizador31.java
Alteração da url RecepcaoEvento  NFCe webservice AM
=> Alterando url RecepcaoEvento NFCe webservice AM

src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoItemImpostoICMSSN900.java, src/test/java/com/fincatto/nfe310/classes/nota/NFNotaInfoItemImpostoICMSSN900Test.java
Atributos como required = false
=> Tratando grupos opcionais no SN 900.

src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoItemImpostoCOFINSAliquota.java, src/main/java/com/fincatto/nfe310/classes/nota/NFNotaInfoItemImpostoPISAliquota.java, src/main/java/com/fincatto/nfe310/webservices/WSManifestacaoDestinatario.java, src/main/java/com/fincatto/nfe310/webservices/WSNotaConsulta.java
Ajustadas situacoes permitidas para objetos de pis e cofins.
=> Cst piscofins

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java
Alterando a url de envio de NFCe da PB. Modificando de HTTPS para HTTP.
=> Modificando URL de cupom do estado da PB

src/main/java/com/fincatto/documentofiscal/nfe310/classes/NFAutorizador31.java
Pernambuco usa SVRS por enquanto. #387
=> [UPD] Alteração URL Pernambuco

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFIndicadorEscalaRelevante.java, src/main/java/com/fincatto/documentofiscal/nfe400/transformers/NFIndicadorEscalaRelevanteTransformer.java, src/main/java/com/fincatto/documentofiscal/transformers/DFRegistryMatcher.java
Corrige erro descrito no [commit](https://github.com/wmixvideo/nfe/commit/d0a84e22494dac8c559959083f082a06a43b7e32)
=>  Adiciona NFIndicadorEscalaRelevante em DFRegistryMatcher para evitar erro.

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProdutoCombustivel.java
Tamanho da Descrição do Código ANP - Entre 2 e 95
Estava fixado 9, provavelmente se basearam no código ANP que é 9.
=> Tamanho da Descrição do Código ANP - Entre 2 e 95

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS60.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS60Test.java
Alterado required para vBCSTRet, pST e vICMSSTRet da classe NFNotaInfoItemImpostoICMS60.java de true para false
=>  Alterado required na classe NFNotaInfoItemImpostoICMS60.java

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFRetornoStatus.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoCartao.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoPagamento.java
O troco estava definido em classe errada.
=> Corrige local do troco em pagamentos conforme Schema XML

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java
Segue modificações em URL's segundo:
[http://www.nfe.ms.gov.br/a-sefaz-ms-informa-que-ocorrera-em-10-07-2018-proxima-terca-feira-alteracao-das-urls-da-versao-4-00-do-ambiente-de-producao-da-nf-e/](http://www.nfe.ms.gov.br/a-sefaz-ms-informa-que-ocorrera-em-10-07-2018-proxima-terca-feira-alteracao-das-urls-da-versao-4-00-do-ambiente-de-producao-da-nf-e/)
&
[http://www.nfce.ms.gov.br/2018/07/05/a-sefaz-ms-informa-que-ocorrera-em-10-07-2018-proxima-terca-feira-alteracao-das-urls-da-versao-4-00-do-ambiente-de-producao-da-nfc-e/](http://www.nfce.ms.gov.br/2018/07/05/a-sefaz-ms-informa-que-ocorrera-em-10-07-2018-proxima-terca-feira-alteracao-das-urls-da-versao-4-00-do-ambiente-de-producao-da-nfc-e/)
=> Novas Url's MS para NF 4.00

README.md
Adiciona como carregar o certificado do repositório do Windows no read-me
=> Adiciona como carregar o certificado do repositório do Windows no read-me

src/main/java/com/fincatto/documentofiscal/assinatura/AssinaturaDigital.java
Foi criada uma versão do assinarDocumento para assinar XMLs grandes que
não estejam em formato String, evitando uso demasiado de memória.
Atualmente utilizo esta classe para assinar XMLs para o [Bloco X](https://www.confaz.fazenda.gov.br/legislacao/despacho/2017/dp137_17) no qual o tamanho deles é comum passar de vários MB o que pode gerar problemas de memória.
=> Método assinarDocumento para XMLs grandes baseado em Reader e Writer

src/main/java/com/fincatto/documentofiscal/mdfe3/classes/nota/MDFProcessado.java, src/main/java/com/fincatto/documentofiscal/parsers/DFParser.java
Adicionado a classe MDFProcessado
=> Adicionado a classe MDFProcessado

pom.xml, src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qtcode/NFGeraQRCode20.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qtcode/NFGeraQRCodeContingenciaOffline20.java, src/main/java/com/fincatto/documentofiscal/nfe400/utils/qtcode/NFGeraQRCodeEmissaoNormal20.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSLoteEnvio.java, src/test/java/com/fincatto/documentofiscal/nfe400/FabricaDeObjetosFake.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFGeraQRCode20Test.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFGeraQRCodeContingenciaOffline20Test.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFGeraQRCodeEmissaoNormal20Test.java
1 - Implementação QRCode 2.0 Emissão Normal
2 - Implementação QRCode 2.0 Contingência Offline
3 - Implementação de testes unitário para emissão normal e contingência Offline.
4 - Correção url consultaChaveAcessoHomologacao e consultaChaveAcessoProducao para o estado de Goiás.
5 - Padronização versão de bibliotecas maven com properties.
Obs.: A implementação da emissão normal é a mesma do @Giancarlofitt, porém como efetuei a implementação da contingência offline estou enviando as duas implementações novamente.
Todos os testes unitário passando.
Testado em produção/homologação para o estado de Goiás.
=> Implementação QRCode 2.0, Emissão Normal (1) (on-line)  e Contingência Offline (9) #510

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/evento/manifestacaodestinatario/NFEventoManifestacaoDestinatario.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/evento/manifestacaodestinatario/NFProtocoloEventoManifestacaoDestinatario.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSManifestacaoDestinatario.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/evento/manifestacaodestinatario/NFEventoManifestacaoTest.java
Necessidade de ter o Protocolo de Manifestação do Destinatário.
=> Protocolo Evento Manifestação Destinatario

src/main/java/com/fincatto/documentofiscal/mdfe3/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/mdfe3/webservices/WSIncluirCondutor.java
Adicionado método incluirCondutorAssinado em WsFacade do MDFe
=> Adicionado método incluirCondutorAssinado em WsFacade do MDFe

src/main/java/com/fincatto/documentofiscal/nfe400/classes/lote/consulta/NFLoteConsultaRetorno.java, src/main/java/com/fincatto/documentofiscal/validadores/StringValidador.java
Adicionado ao validador de placas o formato do mercosul (XXX9X99), já disponível em alguns estados.
=> Atualização do validador para atender placas do mercosul

README.md
Versão anterior não esta mais funcionando
=> Atualizado documentação

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/gerado/NFeAutorizacao4Stub.java, src/test/java/com/fincatto/documentofiscal/DFUnidadeFederativaTest.java
URL QRCODE de Producao e Homologacao em Minas Gerais são iguais.
Corrigido URL Consulta chave de MG
Ajustes classes testes
Referencia: http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/
=> Ajustes url MG

src/main/java/com/fincatto/documentofiscal/DFModelo.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfo.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoCOFINSNaoTributavel.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoPISNaoTributado.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoResponsavelTecnico.java, src/main/java/com/fincatto/documentofiscal/validadores/xsd/XMLValidador.java, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/consReciNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/consSitNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/consStatServ_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/enviNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/inutNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/leiauteConsSitNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/leiauteConsStatServ_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/leiauteInutNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/leiauteNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/nfe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/procInutNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/procNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/retConsReciNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/retConsSitNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/retConsStatServ_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/retEnviNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/retInutNFe_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/tiposBasico_v4.00.xsd, src/main/resources/schemas/PL_009_V4_00_NT_2018_005/xmldsig-core-schema_v1.01.xsd
- Adicionado modelo 59 - CF-e (S@T
- Adicionado validação de OPERACAO_TRIBUTAVEL_SUBSTITUICAO_TRIBUTARIA, no set da situacaoTributaria PIS
- Adicionado validação de OPERACAO_TRIBUTAVEL_SUBSTITUICAO_TRIBUTARIA, no set da situacaoTributaria COFINS
- Adicionado responsável técnico para NFC-e, conforme nota técnica NT_2018_005
=> Adicionado responsável técnico para NFC-e, Validação de ST e modelo documento 59

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS60.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN500.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMS60Test.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN500Test.java
Campo corresponde à Nota Técnica 2018.005 - v 1.30.
=> Insere campo vICMSSubstituto para o ICMS 60 e CSOSN 500

src/main/java/com/fincatto/documentofiscal/DFUnidadeFederativa.java
Modificando URL's de consulta de QR Code conforme o site:
http://nfce.encat.org/consulte-sua-nota-qr-code-versao-2-0/
=> Modificando url de consulta no estado da PB

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSST.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSTTest.java
Adicionando ajustes na classe NFNotaInfoItemImpostoICMSST e na classe de teste conforme NT 2018.005
=> Ajustes de ICMSST conforme NT 2018.005

src/main/java/com/fincatto/documentofiscal/validadores/XMLValidador.java
-> Disponibilizando método  p/ validação de nota 4.00
-> Disponibilizando método p/ validação de XML 4.00 com XSD parametrizado
=> Disponibilizando métodos de validação de XML

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoCOFINSAliquota.java
valorBaseCalulo -> valorBaseCalculo
=> Corrigido erro gramatical

src/main/java/com/fincatto/documentofiscal/utils/DFSocketFactory.java
Parametrizando valor do timeout p/ conexão
=> Parametrizando valor do timeout p/ conexão

src/main/java/com/fincatto/documentofiscal/nfe400/classes/evento/NFInfoEventoRetorno.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFOperadoraCartao.java, src/main/java/com/fincatto/documentofiscal/utils/DFCadeiaCertificados.java
Referente à https://github.com/wmixvideo/nfe/issues/654
=> Adicionadas URLs de RecepcaoEvento e DistribuicaoDFe na geração dos cacerts

README.md
1. Ajuste no badge para ele pegar a última versão no maven central
2. Ajustando o link do README.md que estava quebrado
=> Ajustando o badge e também o link

src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSManifestacaoDestinatario.java
A manifestação do usuário não estava funcionando com cpf, fiz a correção para que funcione. Está funcionando.
=> Correção para que a manifestação do destinatário funcione com cpf.

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFMeioPagamento.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFMeioPagamentoTest.java
Sistema Nota Fiscal Eletrônica
Manual de Orientação do Contribuinte
Anexo I – Leiaute e Regras de Validação da NF-e e da NFC-e
Versão 7.00 – Novembro de 2020
=> Atualização e padronização campo 'tPag' Meio de pagamento 

src/main/java/com/fincatto/documentofiscal/nfe400/webservices/gerado/NFeConsultaProtocolo4Stub.java, src/main/java/com/fincatto/documentofiscal/nfe400/webservices/statusservico/consulta/NfeStatusServico4Stub.java
Corrige issue #689 
Eu só consegui testar essas operações e somente no Sefaz MS.
Em produção elas falhavam e homologação funcionavam. Com essa correçao, agora ambas funcionam.
Por favor, alguém valide nos Sefaz de outros estados para garantir que não quebrou eles.
=> issue #689

src/main/java/com/fincatto/documentofiscal/cte/classes/distribuicao/CTDistribuicaoConsultaNSU.java, src/main/java/com/fincatto/documentofiscal/cte/webservices/distribuicao/WSDistribuicaoCTe.java, src/main/java/com/fincatto/documentofiscal/cte300/webservices/WSFacade.java, src/main/java/com/fincatto/documentofiscal/validadores/DFXMLValidador.java, src/main/resources/schemas/PL_CTeDistDFe_100/distDFeInt_v1.00.xsd, src/main/resources/schemas/PL_CTeDistDFe_100/retDistDFeInt_v1.00.xsd, src/main/resources/schemas/PL_CTeDistDFe_100/tiposDistDFe_v1.00.xsd, src/main/resources/schemas/PL_CTeDistDFe_100/xmldsig-core-schema_v1.01.xsd
Já existia uma consulta implementada, porém ela estava sendo realizada por uma instancia do WSDistribuicaoCTe e não estava disponível no WSFacede do CTe, também não contava com validação de Schema na consulta. Este PR contempla essas melhorias, deixando o método antigo como depreciado.
=> Implementação da Consulta ao WS de distribuição de CTe

src/main/java/com/fincatto/documentofiscal/nfe/webservices/distribuicao/WSDistribuicaoNFe.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java
* Adicao Url consulta protocolo homologacao AM
* Adicao DFSocketFactory a Distribuicao de documentos, devido a erro de falta de certificado no repositorio do java para conexao
=> URL Consulta Protocolo Amazonas e DFSocketFactory distribuicao de documentos

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemProdutoMedicamento.java, src/main/java/com/fincatto/documentofiscal/validadores/DFStringValidador.java, src/test/java/com/fincatto/documentofiscal/validadores/DFStringValidadorTest.java
Realizado ajuste para tratamento NT2016.002 código ANVISA
=> Realizado tratamento para Medicamento código ANVISA conforme NT2016.002

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java
=> Correção endereço dos serviços NFeDistribuicaoDFe e RecepcaoEvento para ambiente de Homologação

src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java
https://github.com/wmixvideo/nfe/issues/815
=> Mudança de endereços homologação issues #815

src/main/java/com/fincatto/documentofiscal/cte400/classes/CTAutorizador400.java, src/test/java/com/fincatto/documentofiscal/cte400/classes/CTAutorizador400Test.java
Atualizei as URLs de todas as UFs, todos os autorizadores publicaram os endereços do ambiente de produção do CT-e 4.00.
=> Incluídas URLs de produção do CT-e 4.00

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFRegimeTributario.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN102.java, src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN900.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFRegimeTributarioTest.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN102Test.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoItemImpostoICMSSN900Test.java
adicionado CRT MEI e removido obrigado de origem em alguns CSOSN para contemplar o schema
=> NT 2024.01

src/main/java/com/fincatto/documentofiscal/nfe400/webservices/WSCancelamento.java
Adicionando tratamento para Evitar NPE no cancelamento de uma nota.
=> Trantando NPE

src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoCartao.java, src/main/java/com/fincatto/documentofiscal/validadores/DFStringValidador.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoCartaoTest.java
Ajuste necessário por conta do schema XML
=> ajustado tag cAut para permitir ate 128 caracteres

src/main/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400.java, src/test/java/com/fincatto/documentofiscal/nfe400/classes/NFAutorizador400Test.java
conforme comunicado do estado:
https://www.sefaz.ce.gov.br/2025/05/27/sefaz-disponibiliza-ambiente-de-producao-da-autorizacao-na-svrs/
=> ajustado urls da NFC-e para o estado do CE
